# Generated by Django 2.2 on 2020-06-30 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_act'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='act',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
